version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    container_name: product-service
    restart: unless-stopped

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"

  payment-service:
    build: ./payment-service
    ports:
      - "5004:5004"

  notification-service:
    build: ./notification-service
    ports:
      - "5005:5005"

