name: Build & Test 3-Tier Microservices App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to DockerHub (optional, if you push images)
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 4: Build all services using docker compose
    - name: Build Docker Compose
      run: docker compose build

    # Step 5: Start all services
    - name: Run Docker Compose
      run: docker compose up -d

    # Step 6: Wait for services to start
    - name: Wait for services
      run: sleep 10

    # Step 7: Test User Service API
    - name: Test User Service
      run: curl http://localhost:5001/users

    # Step 8: Test Product Service API
    - name: Test Product Service
      run: curl http://localhost:5002/products

    # Step 9: Test Order Service API
    - name: Test Order Service
      run: curl http://localhost:5003/orders

    # Step 10: Test Payment Service API
    - name: Test Payment Service
      run: curl http://localhost:5004/payments

    # Step 11: Test Notification Service API
    - name: Test Notification Service
      run: curl http://localhost:5005/notifications

    # Step 12: Stop all services after test
    - name: Stop Services
      run: docker compose down
