name: Build & Test 3-Tier App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run services
        run: docker-compose up -d

      - name: Test user service
        run: curl http://localhost:5001/users

      - name: Test product service
        run: curl http://localhost:5002/products
