name: Frontend Deploy

on:
  push:
    branches:
      - main   # Run workflow only when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # Use GitHub free runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      # Since you don't have your own server, we can't copy to /var/www/html
      # Instead, we upload the build folder as an artifact
      - name: Upload frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: build/
