name: Frontend Deploy

on:
  push:
    branches:
      - main   # Run workflow only when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Use your self-hosted runner (Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy frontend
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
