name: Frontend Deploy

on:
  push:
    branches:
      - main   # Run workflow only when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # GitHub ka free runner use hoga

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Upload production-ready build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
